# Generated by Django 5.2.4 on 2025-09-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organizer',
            new_name='is_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_participant',
        ),
    ]
