# Generated by Django 5.2.4 on 2025-09-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_is_organizer_user_is_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
    ]
