# Generated by Django 5.2.4 on 2025-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_user_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
