# Generated by Django 5.2.4 on 2025-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.TextField(blank=True, default='Nothing', null=True),
        ),
    ]
